INSERT INTO "tag_groups" ("code","label","description","sort_order") VALUES
  ('purpose','목적','시안이 어떤 단계/목적으로 만들어졌는지 구분합니다.',1),
  ('target','대상','클라이언트의 성격을 구분합니다.',2),
  ('field','분야','업종이나 서비스 카테고리를 구분합니다.',3),
  ('screen','화면','무엇을 디자인한 시안인지 구분합니다.',4),
  ('style','스타일','디자인의 분위기와 시각적 톤을 구분합니다.',5),
  ('structure','구조','화면의 레이아웃이나 핵심 UI 패턴을 구분합니다.',6)
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "tag_options" ("group_id","code","label","description","sort_order")
SELECT g.id, v.code, v.label, v.description, v.sort_order
FROM "tag_groups" g
JOIN (VALUES
  ('purpose','proposal','제안','수주/제안 단계에서 방향성을 보여주기 위한 시안',1),
  ('purpose','main','본작업','실제 착수 후 요건을 반영해 제작한 시안',2),
  ('purpose','renewal','리뉴얼','기존 사이트/화면을 새롭게 개편하는 시안',3),
  ('purpose','improvement','개선','일부 영역, 사용성, UI를 개선하는 시안',4),
  ('purpose','operation','운영','배너, 이벤트, 공지 등 운영 목적의 시안',5),
  ('purpose','expansion','확장','기존 서비스에 새로운 페이지나 기능을 추가하는 시안',6),
  ('purpose','test','테스트','내부 검토, 스타일 실험, A/B 비교용 시안',7),
  ('target','gov_office','관공서','시청, 구청, 군청, 행정기관 등',1),
  ('target','public_org','공공기관','공단, 재단, 진흥원, 센터 등',2),
  ('target','education_org','교육기관','학교, 대학, 교육청, 학원 등',3),
  ('target','medical_org','의료기관','병원, 의원, 보건소, 헬스케어 기관',4),
  ('target','enterprise','기업','일반 법인, 중소기업, 대기업',5),
  ('target','brand','브랜드','제품/서비스 브랜드 중심 클라이언트',6),
  ('target','small_biz','소상공인','자영업, 매장, 개인사업자',7),
  ('target','association','협회/단체','협회, 조합, 비영리단체, NGO',8),
  ('target','startup','스타트업','신규 서비스, 플랫폼, IT 기반 초기 기업',9),
  ('target','internal','내부 프로젝트','회사 내부 서비스, 자체 서비스, 사내 시스템',10),
  ('field','public_admin','행정','민원, 정책, 공공서비스, 안내',1),
  ('field','education','교육','교육과정, 학교, 강의, 학습 서비스',2),
  ('field','medical_welfare','의료/복지','병원, 건강, 복지, 돌봄 서비스',3),
  ('field','culture_art','문화/예술','전시, 공연, 박물관, 도서관, 콘텐츠',4),
  ('field','tourism_leisure','관광/레저','여행, 숙박, 축제, 체험, 스포츠',5),
  ('field','manufacturing','제조/산업','제품, 설비, 부품, B2B 산업체',6),
  ('field','it_platform','IT/플랫폼','SaaS, 앱, 웹서비스, 커뮤니티',7),
  ('field','commerce','커머스','쇼핑몰, 상세페이지, 판매/구매',8),
  ('field','finance_insurance','금융/보험','금융상품, 보험, 투자, 상담',9),
  ('field','realestate_construction','부동산/건설','분양, 건설사, 부동산 플랫폼',10),
  ('field','food_beverage','식음료','음식점, 카페, 주류, 프랜차이즈',11),
  ('field','recruit_hr','채용/인재','채용공고, 인재풀, HR 서비스',12),
  ('field','environment_energy','환경/에너지','친환경, 에너지, ESG, 기후 관련',13),
  ('field','media_content','미디어/콘텐츠','뉴스, 매거진, 영상, 콘텐츠 플랫폼',14),
  ('screen','home_main','홈페이지 메인','대표 메인 화면',1),
  ('screen','home_sub','홈페이지 서브','소개, 안내, 콘텐츠성 서브페이지',2),
  ('screen','landing','랜딩페이지','광고/캠페인/전환 중심 단일 페이지',3),
  ('screen','event','이벤트 페이지','프로모션, 참여, 이벤트 안내 페이지',4),
  ('screen','detail','상세페이지','제품, 서비스, 콘텐츠 상세 화면',5),
  ('screen','list','리스트 페이지','게시판, 상품목록, 콘텐츠 목록',6),
  ('screen','search_result','검색/결과 페이지','검색창, 필터, 결과 목록 중심 화면',7),
  ('screen','apply_form','신청/예약 폼','접수, 신청, 예약, 문의 입력 화면',8),
  ('screen','auth','로그인/회원가입','인증 관련 화면',9),
  ('screen','mypage','마이페이지','사용자 정보, 신청내역, 개인화 화면',10),
  ('screen','admin','관리자','CMS, 운영자 관리 화면',11),
  ('screen','dashboard','대시보드','통계, 차트, 현황 관리 화면',12),
  ('screen','app','앱 화면','모바일 앱 UI',13),
  ('screen','banner_popup','배너/팝업','운영 배너, 메인 팝업, 광고 소재',14),
  ('screen','email_notify','이메일/알림','메일 템플릿, 알림 화면',15),
  ('style','trust','신뢰감','안정적이고 공신력 있는 느낌',1),
  ('style','modern','모던','최신 웹 UI 느낌, 정돈된 구성',2),
  ('style','minimal','미니멀','요소를 절제한 단순한 스타일',3),
  ('style','professional','전문적','정보 전달력과 업무성이 강한 스타일',4),
  ('style','friendly','친근한','부드럽고 접근성 좋은 느낌',5),
  ('style','emotional','감성적','이미지, 여백, 문구 중심의 분위기',6),
  ('style','luxury','고급스러운','프리미엄, 고급 브랜드 느낌',7),
  ('style','dynamic','역동적','움직임, 강한 비주얼, 활기 있는 느낌',8),
  ('style','technical','테크니컬','IT, 데이터, 기술 중심 느낌',9),
  ('style','public','공공적','관공서/공공기관에 적합한 정돈된 스타일',10),
  ('style','casual','캐주얼','가볍고 편안한 서비스 느낌',11),
  ('style','kitsch_trendy','키치/트렌디','개성 있고 젊은 감각의 스타일',12),
  ('style','info_centric','정보중심','장식보다 정보 구조가 우선인 스타일',13),
  ('style','visual_centric','비주얼중심','큰 이미지, 그래픽, 영상 중심 스타일',14),
  ('structure','hero','히어로 중심','첫 화면의 큰 비주얼/카피가 중심',1),
  ('structure','card','카드형','콘텐츠를 카드 단위로 나열',2),
  ('structure','list','리스트형','정보를 행 단위 목록으로 정리',3),
  ('structure','grid','그리드형','여러 콘텐츠를 격자 구조로 배치',4),
  ('structure','search','검색중심','검색창, 필터, 결과 탐색이 핵심',5),
  ('structure','booking','예약중심','날짜, 시간, 장소, 인원 선택 구조',6),
  ('structure','apply','신청중심','입력폼과 제출 흐름이 핵심',7),
  ('structure','storytelling','스토리텔링','순차적으로 내용을 설명하는 구조',8),
  ('structure','onepage','원페이지','한 페이지 안에서 섹션별로 전개',9),
  ('structure','tab','탭 구조','카테고리/정보를 탭으로 구분',10),
  ('structure','dashboard','대시보드형','통계, 차트, 요약 카드 중심',11),
  ('structure','map','지도중심','위치, 장소, 지역 정보가 핵심',12),
  ('structure','gallery','갤러리형','이미지나 포트폴리오가 중심',13),
  ('structure','magazine','매거진형','기사, 콘텐츠, 이미지 조합 중심',14),
  ('structure','comparison','비교형','A/B, 상품, 서비스 비교 중심',15),
  ('structure','stepper','단계형','순서대로 진행하는 멀티스텝 구조',16)
) AS v(group_code, code, label, description, sort_order) ON v.group_code = g.code
ON CONFLICT ("group_id","code") DO NOTHING;
